### ISSUE TITLE
Update logger to emit timestamps

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer-api#1]
similar to what was done here: https://github.com/blockstack/gaia/pull/170
log aggregation requires timestamps to conform to the tsdb schema. 

_[Originally posted by @wileyj](https://github.com/blockstackpbc/blockstack-explorer-api/issues/5)_

**Comment by zone117x** [comment]
Closed by https://github.com/blockstack/blockstack-explorer-api/pull/37
