### ISSUE TITLE
Update README to include  redis to Local Development instructions

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-explorer-api#18]

**Comment by moxiegirl** [comment]
@zone117x Just curious here, where do we have setup instructions for the explorer? Do you mean the *Local Development* section in the readme?

**Comment by zone117x** [comment]
Thanks @moxiegirl, updated the issue

**Comment by moxiegirl** [comment]
@zone117x If you have rough instructions for this, I can take a look at making this change.
