### ISSUE TITLE
Some naming and keys missing

### ISSUE THREAD

**Issue by markmhx** [blockstack/blockstack-explorer-api#3]
As [originally posted by @aulneau](https://github.com/blockstackpbc/blockstack-explorer-api/issues/1) in deprecated repo (see conversation on that issue for more context and input):

---

```jsx
const tx = {
      address: "mrifWsShtgpyQ7kUpPQFvuddZ2vzbDaQxc", // should this be named sender?
      block_id: 549703,
      credit_value: "100", // what does this mean? is this balance at time of tx?
      debit_value: "10",
      lock_transfer_block_id: 0,
      txid: "fca73d510b083311291623773a69febf0dd236e395f1aeab64bf197ce0111ad9",
      type: "STACKS",
      vtxindex: 1091, // what is this?
      operationType: "$",
      consensusHash: "038a1541a4f314ae37cf3e43d3ad3e54",
      tokenType: "STACKS",
      tokensSent: "10",
      scratchData: "",
      recipientBitcoinAddress: "1BXSdgcRLtrjw5AXZPe1eawmQr75qckfMo",
      recipient: "SP1SQ68HK9N4GFT3CG694FBFAYWS28C39NF1TZG9X",
      tokenSentHex: "000000000000000a",
      tokensSentSTX: "0", // what is this?
      operation: "SENT" // what is the opposite operation? 'RECEIVED'?
    }
```

We should also include a `confirmed` key with a timestamp of the confirmation.

**Comment by jcnelson** [comment]
`credit_value` is the sum of all credits applied to the address.  `debit_value` is the sum of all debits applied to the address.  The address's balance is `credit_value` - `debit_value`.

`vtxindex` is the _offset_ in the block where the transaction occurs (i.e. this is the 1091st transaction in the block).

Not sure what `tokensSentSTX` and `operation` are.

**Comment by zone117x** [comment]
This should no longer be a bug
