### ISSUE TITLE
Efficient cache updating with pub/sub pattern

### ISSUE THREAD

**Issue by zone117x** [blockstack/blockstack-explorer-api#30]
The two primary data ingest sources are Postgres (for Stacks related data) and mongoDB (for bitcoin related data). The Stacks 2.0 data-stream sidecar will also likely be using Postgres. 

Both these data stores support building an architecture with an efficient cache maintenance service using their pub/sub features.

This is the [`LISTEN` and `NOTIFY` features](https://www.postgresql.org/docs/current/libpq-notify.html) in Postgres, and the [`Change Streams` features](https://docs.mongodb.com/manual/changeStreams/) in MongoDB. 

The Explorer will likely require this architecture for the Stacks 2.0 upgrades. The Explorer's existing aggregator-cache pattern can be augmented to build out this architecture. 

For more context on pub/sub cache maintenance, see this article, which outlines how to architect such a system with Postgres: https://tapoueh.org/blog/2018/07/postgresql-listen-notify/

> PostgreSQL LISTEN and NOTIFY support is perfect for maintaining a cache. Because notifications are only delivered to client connections that are listening at the moment of the notify call, our cache maintenance service must implement the following behavior, in this exact order:
> 
> 1. Connect to the PostgreSQL database we expect notifications from and issue the listen command.
> 
> 2. Fetch the current values from their _single source of truth_ and reset the cache with those computed values.
> 
> 3. Process notifications as they come and update the in-memory cache, and once in a while synchronize the in-memory cache to its materialized location, as per the cache invalidation policy.

**Comment by jeffdomke** [comment]
Sounds like we want a bit more detail and background on the problem, alternatives, etc. then a meeting for feedback and agreement.

**Comment by diwakergupta** [comment]
FWIW I think most folks are familiar with the general problem. My recommendation to write down a design doc is 1) for transparency and 2) for alignment -- will help make sure everyone understands the problem and is on the same page w.r.t the solution, and also give us an opportunity the pressure-test the proposed solution.

In terms of what constitutes a good design doc, I'd include:
* a clear, succinct problem statement -- helpful to be explicit about the "why"
* goals / requirements from a solution. Sometimes it's helpful to also articulate any non-goals.
* proposed solution. Consider including any alternate solutions that were considered and rejected; describe any trade-offs this solution is deliberately making
* any specific questions / concerns / risks / unknowns you need feedback on, or any decisions we need to make

Keep the doc simple and to the point, I'm definitely not intending to create any extra work. Hopefully this produces a useful artifact and is generally a good exercise for teams. We can send the doc as a pre-read and focus the meeting on discussion / decisions.

**Comment by jeffdomke** [comment]
Think is was discussed in full at our last meeting. Closing. Feel free to correct me @zone117x
