### ISSUE TITLE
Update total supply

### ISSUE THREAD

**Issue by diwakergupta** [blockstack/blockstack-explorer-api#35]
Current value doesn't capture tokens materialized in the latest hard-fork.

**Comment by timstackblock** [comment]
{
  "unlockedPercent": "37.63",
  "totalStacks": "1352464600.000000",
  "totalStacksFormatted": "1,352,464,600.000000",
  "unlockedSupply": "508906194.335980",
  "unlockedSupplyFormatted": "508,906,194.335980",
  "blockHeight": "616413"
}



<img width="493" alt="Screen Shot 2020-02-10 at 4 37 54 PM" src="https://user-images.githubusercontent.com/49165468/74192653-ef440480-4c23-11ea-9608-30bae984b3ba.png">
